# Generated by Django 4.2.20 on 2025-05-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iso_code", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="EconomicBloc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TradeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=0)),
                ("export_value", models.FloatField()),
                ("import_value", models.FloatField()),
                ("trade_balance", models.FloatField()),
                ("gdp_share", models.FloatField()),
                ("world_trade_share", models.FloatField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("year", models.PositiveSmallIntegerField(default=0)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountryBlocMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "bloc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.economicbloc",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.country",
                    ),
                ),
            ],
        ),
    ]
